/*
 * SPDX-FileCopyrightText: Copyright 2026 Arm Limited and/or its affiliates <open-source-office@arm.com>
 * SPDX-License-Identifier: MIT OR (Apache-2.0 WITH LLVM-exception)
 */

#ifndef _PERFLIBS_BLAS_H
#define _PERFLIBS_BLAS_H

#include "pl_linalg_int.h"
#include "pl_linalg_float.h"
#include "pl_linalg_complex.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

/* BLAS routines */
void caxpby_(const pl_linalg_int_t *n, const pl_linalg_singlecomplex_t *alpha, const pl_linalg_singlecomplex_t *x, const pl_linalg_int_t *incx, const pl_linalg_singlecomplex_t *beta, pl_linalg_singlecomplex_t *y, const pl_linalg_int_t *incy);
void caxpy_(const pl_linalg_int_t *n, const pl_linalg_singlecomplex_t *alpha, const pl_linalg_singlecomplex_t *x, const pl_linalg_int_t *incx, pl_linalg_singlecomplex_t *y, const pl_linalg_int_t *incy);
void ccopy_(const pl_linalg_int_t *n, const pl_linalg_singlecomplex_t *x, const pl_linalg_int_t *incx, pl_linalg_singlecomplex_t *y, const pl_linalg_int_t *incy);
#if !defined(PL_LINALG_AVOID_SINGLECOMPLEX_RETURN)
pl_linalg_singlecomplex_t cdotc_(const pl_linalg_int_t *n, const pl_linalg_singlecomplex_t *x, const pl_linalg_int_t *incx, const pl_linalg_singlecomplex_t *y, const pl_linalg_int_t *incy);
pl_linalg_singlecomplex_t cdotu_(const pl_linalg_int_t *n, const pl_linalg_singlecomplex_t *x, const pl_linalg_int_t *incx, const pl_linalg_singlecomplex_t *y, const pl_linalg_int_t *incy);
#endif
void cgbmv_(const char *trans, const pl_linalg_int_t *m, const pl_linalg_int_t *n, const pl_linalg_int_t *kl, const pl_linalg_int_t *ku, const pl_linalg_singlecomplex_t *alpha, const pl_linalg_singlecomplex_t *a, const pl_linalg_int_t *lda, const pl_linalg_singlecomplex_t *x, const pl_linalg_int_t *incx, const pl_linalg_singlecomplex_t *beta, pl_linalg_singlecomplex_t *y, const pl_linalg_int_t *incy, ... );
void cgemm_(const char *transa, const char *transb, const pl_linalg_int_t *m, const pl_linalg_int_t *n, const pl_linalg_int_t *k, const pl_linalg_singlecomplex_t *alpha, const pl_linalg_singlecomplex_t *a, const pl_linalg_int_t *lda, const pl_linalg_singlecomplex_t *b, const pl_linalg_int_t *ldb, const pl_linalg_singlecomplex_t *beta, pl_linalg_singlecomplex_t *c, const pl_linalg_int_t *ldc, ... );
void cgemm3m_(const char *transa, const char *transb, const pl_linalg_int_t *m, const pl_linalg_int_t *n, const pl_linalg_int_t *k, const pl_linalg_singlecomplex_t *alpha, const pl_linalg_singlecomplex_t *a, const pl_linalg_int_t *lda, const pl_linalg_singlecomplex_t *b, const pl_linalg_int_t *ldb, const pl_linalg_singlecomplex_t *beta, pl_linalg_singlecomplex_t *c, const pl_linalg_int_t *ldc, ... );
void cgemm_batch_(const char *transa, const char *transb, const pl_linalg_int_t *m, const pl_linalg_int_t *n, const pl_linalg_int_t *k, const pl_linalg_singlecomplex_t *alpha, const pl_linalg_singlecomplex_t *const *a, const pl_linalg_int_t *lda, const pl_linalg_singlecomplex_t *const *b, const pl_linalg_int_t *ldb, const pl_linalg_singlecomplex_t *beta, pl_linalg_singlecomplex_t *const *c, const pl_linalg_int_t *ldc, const pl_linalg_int_t *group_count, const pl_linalg_int_t *group_size, ... );
void cgemmt_(const char *uplo, const char *transa, const char *transb, const pl_linalg_int_t *n, const pl_linalg_int_t *k, const pl_linalg_singlecomplex_t *alpha, const pl_linalg_singlecomplex_t *a, const pl_linalg_int_t *lda, const pl_linalg_singlecomplex_t *b, const pl_linalg_int_t *ldb, const pl_linalg_singlecomplex_t *beta, pl_linalg_singlecomplex_t *c, const pl_linalg_int_t *ldc, ... );
void cgemmtr_(const char *uplo, const char *transa, const char *transb, const pl_linalg_int_t *n, const pl_linalg_int_t *k, const pl_linalg_singlecomplex_t *alpha, const pl_linalg_singlecomplex_t *a, const pl_linalg_int_t *lda, const pl_linalg_singlecomplex_t *b, const pl_linalg_int_t *ldb, const pl_linalg_singlecomplex_t *beta, pl_linalg_singlecomplex_t *c, const pl_linalg_int_t *ldc, ... );
void cgemv_(const char *trans, const pl_linalg_int_t *m, const pl_linalg_int_t *n, const pl_linalg_singlecomplex_t *alpha, const pl_linalg_singlecomplex_t *a, const pl_linalg_int_t *lda, const pl_linalg_singlecomplex_t *x, const pl_linalg_int_t *incx, const pl_linalg_singlecomplex_t *beta, pl_linalg_singlecomplex_t *y, const pl_linalg_int_t *incy, ... );
void cgerbc_(const pl_linalg_int_t *m, const pl_linalg_int_t *n, const pl_linalg_singlecomplex_t *alpha, const pl_linalg_singlecomplex_t *x, const pl_linalg_int_t *incx, const pl_linalg_singlecomplex_t *y, const pl_linalg_int_t *incy, const pl_linalg_singlecomplex_t *beta, pl_linalg_singlecomplex_t *a, const pl_linalg_int_t *lda);
void cgerbu_(const pl_linalg_int_t *m, const pl_linalg_int_t *n, const pl_linalg_singlecomplex_t *alpha, const pl_linalg_singlecomplex_t *x, const pl_linalg_int_t *incx, const pl_linalg_singlecomplex_t *y, const pl_linalg_int_t *incy, const pl_linalg_singlecomplex_t *beta, pl_linalg_singlecomplex_t *a, const pl_linalg_int_t *lda);
void cgerc_(const pl_linalg_int_t *m, const pl_linalg_int_t *n, const pl_linalg_singlecomplex_t *alpha, const pl_linalg_singlecomplex_t *x, const pl_linalg_int_t *incx, const pl_linalg_singlecomplex_t *y, const pl_linalg_int_t *incy, pl_linalg_singlecomplex_t *a, const pl_linalg_int_t *lda);
void cgeru_(const pl_linalg_int_t *m, const pl_linalg_int_t *n, const pl_linalg_singlecomplex_t *alpha, const pl_linalg_singlecomplex_t *x, const pl_linalg_int_t *incx, const pl_linalg_singlecomplex_t *y, const pl_linalg_int_t *incy, pl_linalg_singlecomplex_t *a, const pl_linalg_int_t *lda);
void chbmv_(const char *uplo, const pl_linalg_int_t *n, const pl_linalg_int_t *k, const pl_linalg_singlecomplex_t *alpha, const pl_linalg_singlecomplex_t *a, const pl_linalg_int_t *lda, const pl_linalg_singlecomplex_t *x, const pl_linalg_int_t *incx, const pl_linalg_singlecomplex_t *beta, pl_linalg_singlecomplex_t *y, const pl_linalg_int_t *incy, ... );
void chemm_(const char *side, const char *uplo, const pl_linalg_int_t *m, const pl_linalg_int_t *n, const pl_linalg_singlecomplex_t *alpha, const pl_linalg_singlecomplex_t *a, const pl_linalg_int_t *lda, const pl_linalg_singlecomplex_t *b, const pl_linalg_int_t *ldb, const pl_linalg_singlecomplex_t *beta, pl_linalg_singlecomplex_t *c, const pl_linalg_int_t *ldc, ... );
void chemv_(const char *uplo, const pl_linalg_int_t *n, const pl_linalg_singlecomplex_t *alpha, const pl_linalg_singlecomplex_t *a, const pl_linalg_int_t *lda, const pl_linalg_singlecomplex_t *x, const pl_linalg_int_t *incx, const pl_linalg_singlecomplex_t *beta, pl_linalg_singlecomplex_t *y, const pl_linalg_int_t *incy, ... );
void cher2_(const char *uplo, const pl_linalg_int_t *n, const pl_linalg_singlecomplex_t *alpha, const pl_linalg_singlecomplex_t *x, const pl_linalg_int_t *incx, const pl_linalg_singlecomplex_t *y, const pl_linalg_int_t *incy, pl_linalg_singlecomplex_t *a, const pl_linalg_int_t *lda, ... );
void cher2k_(const char *uplo, const char *trans, const pl_linalg_int_t *n, const pl_linalg_int_t *k, const pl_linalg_singlecomplex_t *alpha, const pl_linalg_singlecomplex_t *a, const pl_linalg_int_t *lda, const pl_linalg_singlecomplex_t *b, const pl_linalg_int_t *ldb, const float *beta, pl_linalg_singlecomplex_t *c, const pl_linalg_int_t *ldc, ... );
void cher_(const char *uplo, const pl_linalg_int_t *n, const float *alpha, const pl_linalg_singlecomplex_t *x, const pl_linalg_int_t *incx, pl_linalg_singlecomplex_t *a, const pl_linalg_int_t *lda, ... );
void cherk_(const char *uplo, const char *trans, const pl_linalg_int_t *n, const pl_linalg_int_t *k, const float *alpha, const pl_linalg_singlecomplex_t *a, const pl_linalg_int_t *lda, const float *beta, pl_linalg_singlecomplex_t *c, const pl_linalg_int_t *ldc, ... );
void chpmv_(const char *uplo, const pl_linalg_int_t *n, const pl_linalg_singlecomplex_t *alpha, const pl_linalg_singlecomplex_t *a, const pl_linalg_singlecomplex_t *x, const pl_linalg_int_t *incx, const pl_linalg_singlecomplex_t *beta, pl_linalg_singlecomplex_t *y, const pl_linalg_int_t *incy, ... );
void chpr2_(const char *uplo, const pl_linalg_int_t *n, const pl_linalg_singlecomplex_t *alpha, const pl_linalg_singlecomplex_t *x, const pl_linalg_int_t *incx, const pl_linalg_singlecomplex_t *y, const pl_linalg_int_t *incy, pl_linalg_singlecomplex_t *a, ... );
void chpr_(const char *uplo, const pl_linalg_int_t *n, const float *alpha, const pl_linalg_singlecomplex_t *x, const pl_linalg_int_t *incx, pl_linalg_singlecomplex_t *a, ... );
void crotg_(pl_linalg_singlecomplex_t *ca, const pl_linalg_singlecomplex_t *cb, float *c, pl_linalg_singlecomplex_t *s);
void csbmv_(const char *uplo, const pl_linalg_int_t *n, const pl_linalg_int_t *k, const pl_linalg_singlecomplex_t *alpha, const pl_linalg_singlecomplex_t *a, const pl_linalg_int_t *lda, const pl_linalg_singlecomplex_t *x, const pl_linalg_int_t *incx, const pl_linalg_singlecomplex_t *beta, pl_linalg_singlecomplex_t *y, const pl_linalg_int_t *incy, ... );
void cscal_(const pl_linalg_int_t *n, const pl_linalg_singlecomplex_t *alpha, pl_linalg_singlecomplex_t *x, const pl_linalg_int_t *incx);
void csrot_(const pl_linalg_int_t *n, pl_linalg_singlecomplex_t *x, const pl_linalg_int_t *incx, pl_linalg_singlecomplex_t *y, const pl_linalg_int_t *incy, const float *c, const float *s);
void csscal_(const pl_linalg_int_t *n, const float *alpha, pl_linalg_singlecomplex_t *x, const pl_linalg_int_t *incx);
void cswap_(const pl_linalg_int_t *n, pl_linalg_singlecomplex_t *x, const pl_linalg_int_t *incx, pl_linalg_singlecomplex_t *y, const pl_linalg_int_t *incy);
void csymm_(const char *side, const char *uplo, const pl_linalg_int_t *m, const pl_linalg_int_t *n, const pl_linalg_singlecomplex_t *alpha, const pl_linalg_singlecomplex_t *a, const pl_linalg_int_t *lda, const pl_linalg_singlecomplex_t *b, const pl_linalg_int_t *ldb, const pl_linalg_singlecomplex_t *beta, pl_linalg_singlecomplex_t *c, const pl_linalg_int_t *ldc, ... );
void csyr2k_(const char *uplo, const char *trans, const pl_linalg_int_t *n, const pl_linalg_int_t *k, const pl_linalg_singlecomplex_t *alpha, const pl_linalg_singlecomplex_t *a, const pl_linalg_int_t *lda, const pl_linalg_singlecomplex_t *b, const pl_linalg_int_t *ldb, const pl_linalg_singlecomplex_t *beta, pl_linalg_singlecomplex_t *c, const pl_linalg_int_t *ldc, ... );
void csyrk_(const char *uplo, const char *trans, const pl_linalg_int_t *n, const pl_linalg_int_t *k, const pl_linalg_singlecomplex_t *alpha, const pl_linalg_singlecomplex_t *a, const pl_linalg_int_t *lda, const pl_linalg_singlecomplex_t *beta, pl_linalg_singlecomplex_t *c, const pl_linalg_int_t *ldc, ... );
void ctbmv_(const char *uplo, const char *trans, const char *diag, const pl_linalg_int_t *n, const pl_linalg_int_t *k, const pl_linalg_singlecomplex_t *a, const pl_linalg_int_t *lda, pl_linalg_singlecomplex_t *x, const pl_linalg_int_t *incx, ... );
void ctbsv_(const char *uplo, const char *trans, const char *diag, const pl_linalg_int_t *n, const pl_linalg_int_t *k, const pl_linalg_singlecomplex_t *a, const pl_linalg_int_t *lda, pl_linalg_singlecomplex_t *x, const pl_linalg_int_t *incx, ... );
void ctpmv_(const char *uplo, const char *trans, const char *diag, const pl_linalg_int_t *n, const pl_linalg_singlecomplex_t *ap, pl_linalg_singlecomplex_t *x, const pl_linalg_int_t *incx, ... );
void ctpsv_(const char *uplo, const char *trans, const char *diag, const pl_linalg_int_t *n, const pl_linalg_singlecomplex_t *ap, pl_linalg_singlecomplex_t *x, const pl_linalg_int_t *incx, ... );
void ctrmm_(const char *side, const char *uplo, const char *transa, const char *diag, const pl_linalg_int_t *m, const pl_linalg_int_t *n, const pl_linalg_singlecomplex_t *alpha, const pl_linalg_singlecomplex_t *a, const pl_linalg_int_t *lda, pl_linalg_singlecomplex_t *b, const pl_linalg_int_t *ldb, ... );
void ctrmv_(const char *uplo, const char *trans, const char *diag, const pl_linalg_int_t *n, const pl_linalg_singlecomplex_t *a, const pl_linalg_int_t *lda, pl_linalg_singlecomplex_t *x, const pl_linalg_int_t *incx, ... );
void ctrsm_(const char *side, const char *uplo, const char *transa, const char *diag, const pl_linalg_int_t *m, const pl_linalg_int_t *n, const pl_linalg_singlecomplex_t *alpha, const pl_linalg_singlecomplex_t *a, const pl_linalg_int_t *lda, pl_linalg_singlecomplex_t *b, const pl_linalg_int_t *ldb, ... );
void ctrsv_(const char *uplo, const char *trans, const char *diag, const pl_linalg_int_t *n, const pl_linalg_singlecomplex_t *a, const pl_linalg_int_t *lda, pl_linalg_singlecomplex_t *x, const pl_linalg_int_t *incx, ... );
void cwaxpby_(const pl_linalg_int_t *n, const pl_linalg_singlecomplex_t *alpha, const pl_linalg_singlecomplex_t *x, const pl_linalg_int_t *incx, const pl_linalg_singlecomplex_t *beta, const pl_linalg_singlecomplex_t *y, const pl_linalg_int_t *incy, pl_linalg_singlecomplex_t *w, const pl_linalg_int_t *incw);
double dasum_(const pl_linalg_int_t *n, const double *x, const pl_linalg_int_t *incx);
void daxpby_(const pl_linalg_int_t *n, const double *alpha, const double *x, const pl_linalg_int_t *incx, const double *beta, double *y, const pl_linalg_int_t *incy);
void daxpy_(const pl_linalg_int_t *n, const double *alpha, const double *x, const pl_linalg_int_t *incx, double *y, const pl_linalg_int_t *incy);
double dcabs1_(const pl_linalg_doublecomplex_t *z);
void dcopy_(const pl_linalg_int_t *n, const double *x, const pl_linalg_int_t *incx, double *y, const pl_linalg_int_t *incy);
double ddot_(const pl_linalg_int_t *n, const double *x, const pl_linalg_int_t *incx, const double *y, const pl_linalg_int_t *incy);
void dgbmv_(const char *trans, const pl_linalg_int_t *m, const pl_linalg_int_t *n, const pl_linalg_int_t *kl, const pl_linalg_int_t *ku, const double *alpha, const double *a, const pl_linalg_int_t *lda, const double *x, const pl_linalg_int_t *incx, const double *beta, double *y, const pl_linalg_int_t *incy, ... );
void dgemm_(const char *transa, const char *transb, const pl_linalg_int_t *m, const pl_linalg_int_t *n, const pl_linalg_int_t *k, const double *alpha, const double *a, const pl_linalg_int_t *lda, const double *b, const pl_linalg_int_t *ldb, const double *beta, double *c, const pl_linalg_int_t *ldc, ... );
void dgemm_batch_(const char *transa, const char *transb, const pl_linalg_int_t *m, const pl_linalg_int_t *n, const pl_linalg_int_t *k, const double *alpha, const double *const *a, const pl_linalg_int_t *lda, const double *const *b, const pl_linalg_int_t *ldb, const double *beta, double *const *c, const pl_linalg_int_t *ldc, const pl_linalg_int_t *group_count, const pl_linalg_int_t *group_size, ... );
void dgemmt_(const char *uplo, const char *transa, const char *transb, const pl_linalg_int_t *n, const pl_linalg_int_t *k, const double *alpha, const double *a, const pl_linalg_int_t *lda, const double *b, const pl_linalg_int_t *ldb, const double *beta, double *c, const pl_linalg_int_t *ldc, ... );
void dgemmtr_(const char *uplo, const char *transa, const char *transb, const pl_linalg_int_t *n, const pl_linalg_int_t *k, const double *alpha, const double *a, const pl_linalg_int_t *lda, const double *b, const pl_linalg_int_t *ldb, const double *beta, double *c, const pl_linalg_int_t *ldc, ... );
void dgemv_(const char *trans, const pl_linalg_int_t *m, const pl_linalg_int_t *n, const double *alpha, const double *a, const pl_linalg_int_t *lda, const double *x, const pl_linalg_int_t *incx, const double *beta, double *y, const pl_linalg_int_t *incy, ... );
void dger_(const pl_linalg_int_t *m, const pl_linalg_int_t *n, const double *alpha, const double *x, const pl_linalg_int_t *incx, const double *y, const pl_linalg_int_t *incy, double *a, const pl_linalg_int_t *lda);
void dgerb_(const pl_linalg_int_t *m, const pl_linalg_int_t *n, const double *alpha, const double *x, const pl_linalg_int_t *incx, const double *y, const pl_linalg_int_t *incy, const double *beta, double *a, const pl_linalg_int_t *lda);
double dnrm2_(const pl_linalg_int_t *n, const double *x, const pl_linalg_int_t *incx);
void drot_(const pl_linalg_int_t *n, double *x, const pl_linalg_int_t *incx, double *y, const pl_linalg_int_t *incy, const double *c, const double *s);
void drotg_(double *a, double *b, double *c, double *s);
void drotm_(const pl_linalg_int_t *n, double *x, const pl_linalg_int_t *incx, double *y, const pl_linalg_int_t *incy, const double *param);
void drotmg_(double *d1, double *d2, double *b1, const double *b2, double *param);
void dsbmv_(const char *uplo, const pl_linalg_int_t *n, const pl_linalg_int_t *k, const double *alpha, const double *a, const pl_linalg_int_t *lda, const double *x, const pl_linalg_int_t *incx, const double *beta, double *y, const pl_linalg_int_t *incy, ... );
void dscal_(const pl_linalg_int_t *n, const double *alpha, double *x, const pl_linalg_int_t *incx);
double dsdot_(const pl_linalg_int_t *n, const float *sx, const pl_linalg_int_t *incx, const float *sy, const pl_linalg_int_t *incy);
void dspmv_(const char *uplo, const pl_linalg_int_t *n, const double *alpha, const double *ap, const double *x, const pl_linalg_int_t *incx, const double *beta, double *y, const pl_linalg_int_t *incy, ... );
void dspr2_(const char *uplo, const pl_linalg_int_t *n, const double *alpha, const double *x, const pl_linalg_int_t *incx, const double *y, const pl_linalg_int_t *incy, double *ap, ... );
void dspr_(const char *uplo, const pl_linalg_int_t *n, const double *alpha, const double *x, const pl_linalg_int_t *incx, double *ap, ... );
void dswap_(const pl_linalg_int_t *n, double *x, const pl_linalg_int_t *incx, double *y, const pl_linalg_int_t *incy);
void dsymm_(const char *side, const char *uplo, const pl_linalg_int_t *m, const pl_linalg_int_t *n, const double *alpha, const double *a, const pl_linalg_int_t *lda, const double *b, const pl_linalg_int_t *ldb, const double *beta, double *c, const pl_linalg_int_t *ldc, ... );
void dsymv_(const char *uplo, const pl_linalg_int_t *n, const double *alpha, const double *a, const pl_linalg_int_t *lda, const double *x, const pl_linalg_int_t *incx, const double *beta, double *y, const pl_linalg_int_t *incy, ... );
void dsyr2_(const char *uplo, const pl_linalg_int_t *n, const double *alpha, const double *x, const pl_linalg_int_t *incx, const double *y, const pl_linalg_int_t *incy, double *a, const pl_linalg_int_t *lda, ... );
void dsyr2k_(const char *uplo, const char *trans, const pl_linalg_int_t *n, const pl_linalg_int_t *k, const double *alpha, const double *a, const pl_linalg_int_t *lda, const double *b, const pl_linalg_int_t *ldb, const double *beta, double *c, const pl_linalg_int_t *ldc, ... );
void dsyr_(const char *uplo, const pl_linalg_int_t *n, const double *alpha, const double *x, const pl_linalg_int_t *incx, double *a, const pl_linalg_int_t *lda, ... );
void dsyrk_(const char *uplo, const char *trans, const pl_linalg_int_t *n, const pl_linalg_int_t *k, const double *alpha, const double *a, const pl_linalg_int_t *lda, const double *beta, double *c, const pl_linalg_int_t *ldc, ... );
void dtbmv_(const char *uplo, const char *trans, const char *diag, const pl_linalg_int_t *n, const pl_linalg_int_t *k, const double *a, const pl_linalg_int_t *lda, double *x, const pl_linalg_int_t *incx, ... );
void dtbsv_(const char *uplo, const char *trans, const char *diag, const pl_linalg_int_t *n, const pl_linalg_int_t *k, const double *a, const pl_linalg_int_t *lda, double *x, const pl_linalg_int_t *incx, ... );
void dtpmv_(const char *uplo, const char *trans, const char *diag, const pl_linalg_int_t *n, const double *ap, double *x, const pl_linalg_int_t *incx, ... );
void dtpsv_(const char *uplo, const char *trans, const char *diag, const pl_linalg_int_t *n, const double *ap, double *x, const pl_linalg_int_t *incx, ... );
void dtrmm_(const char *side, const char *uplo, const char *transa, const char *diag, const pl_linalg_int_t *m, const pl_linalg_int_t *n, const double *alpha, const double *a, const pl_linalg_int_t *lda, double *b, const pl_linalg_int_t *ldb, ... );
void dtrmv_(const char *uplo, const char *trans, const char *diag, const pl_linalg_int_t *n, const double *a, const pl_linalg_int_t *lda, double *x, const pl_linalg_int_t *incx, ... );
void dtrsm_(const char *side, const char *uplo, const char *transa, const char *diag, const pl_linalg_int_t *m, const pl_linalg_int_t *n, const double *alpha, const double *a, const pl_linalg_int_t *lda, double *b, const pl_linalg_int_t *ldb, ... );
void dtrsv_(const char *uplo, const char *trans, const char *diag, const pl_linalg_int_t *n, const double *a, const pl_linalg_int_t *lda, double *x, const pl_linalg_int_t *incx, ... );
void dwaxpby_(const pl_linalg_int_t *n, const double *alpha, const double *x, const pl_linalg_int_t *incx, const double *beta, const double *y, const pl_linalg_int_t *incy, double *w, const pl_linalg_int_t *incw);
double dzasum_(const pl_linalg_int_t *n, const pl_linalg_doublecomplex_t *x, const pl_linalg_int_t *incx);
double dznrm2_(const pl_linalg_int_t *n, const pl_linalg_doublecomplex_t *x, const pl_linalg_int_t *incx);
pl_linalg_int_t icamax_(const pl_linalg_int_t *n, const pl_linalg_singlecomplex_t *x, const pl_linalg_int_t *incx);
pl_linalg_int_t idamax_(const pl_linalg_int_t *n, const double *x, const pl_linalg_int_t *incx);
pl_linalg_int_t isamax_(const pl_linalg_int_t *n, const float *x, const pl_linalg_int_t *incx);
pl_linalg_int_t izamax_(const pl_linalg_int_t *n, const pl_linalg_doublecomplex_t *x, const pl_linalg_int_t *incx);
pl_linalg_int_t icamin_(const pl_linalg_int_t *n, const pl_linalg_singlecomplex_t *x, const pl_linalg_int_t *incx);
pl_linalg_int_t idamin_(const pl_linalg_int_t *n, const double *x, const pl_linalg_int_t *incx);
pl_linalg_int_t isamin_(const pl_linalg_int_t *n, const float *x, const pl_linalg_int_t *incx);
pl_linalg_int_t izamin_(const pl_linalg_int_t *n, const pl_linalg_doublecomplex_t *x, const pl_linalg_int_t *incx);
pl_linalg_int_t lsame_(const char *ca, const char *cb, ... );
float sasum_(const pl_linalg_int_t *n, const float *x, const pl_linalg_int_t *incx);
void saxpby_(const pl_linalg_int_t *n, const float *alpha, const float *x, const pl_linalg_int_t *incx, const float *beta, float *y, const pl_linalg_int_t *incy);
void saxpy_(const pl_linalg_int_t *n, const float *alpha, const float *x, const pl_linalg_int_t *incx, float *y, const pl_linalg_int_t *incy);
float scabs1_(const pl_linalg_singlecomplex_t *c);
float scasum_(const pl_linalg_int_t *n, const pl_linalg_singlecomplex_t *x, const pl_linalg_int_t *incx);
float scnrm2_(const pl_linalg_int_t *n, const pl_linalg_singlecomplex_t *x, const pl_linalg_int_t *incx);
void scopy_(const pl_linalg_int_t *n, const float *x, const pl_linalg_int_t *incx, float *y, const pl_linalg_int_t *incy);
float sdot_(const pl_linalg_int_t *n, const float *x, const pl_linalg_int_t *incx, const float *y, const pl_linalg_int_t *incy);
float sdsdot_(const pl_linalg_int_t *n, const float *b, const float *x, const pl_linalg_int_t *incx, const float *y, const pl_linalg_int_t *incy);
void sgbmv_(const char *trans, const pl_linalg_int_t *m, const pl_linalg_int_t *n, const pl_linalg_int_t *kl, const pl_linalg_int_t *ku, const float *alpha, const float *a, const pl_linalg_int_t *lda, const float *x, const pl_linalg_int_t *incx, const float *beta, float *y, const pl_linalg_int_t *incy, ... );
void sbaxpby_(const pl_linalg_int_t *n, const float *alpha, const pl_linalg_bf16_t *x, const pl_linalg_int_t *incx, const float *beta, float *y, const pl_linalg_int_t *incy);
void sbaxpy_(const pl_linalg_int_t *n, const float *alpha, const pl_linalg_bf16_t *x, const pl_linalg_int_t *incx, float *y, const pl_linalg_int_t *incy);
void sbcopy_(const pl_linalg_int_t *n, const pl_linalg_bf16_t *x, const pl_linalg_int_t *incx, float *y, const pl_linalg_int_t *incy);
float sbdot_(const pl_linalg_int_t *n, const pl_linalg_bf16_t *x, const pl_linalg_int_t *incx, const pl_linalg_bf16_t *y, const pl_linalg_int_t *incy);
void sbgemm_(const char *transa, const char *transb, const pl_linalg_int_t *m, const pl_linalg_int_t *n, const pl_linalg_int_t *k, const float *alpha, const pl_linalg_bf16_t *a, const pl_linalg_int_t *lda, const pl_linalg_bf16_t *b, const pl_linalg_int_t *ldb, const float *beta, float *c, const pl_linalg_int_t *ldc, ... );
void sbgemv_(const char *trans, const pl_linalg_int_t *m, const pl_linalg_int_t *n, const float *alpha, const pl_linalg_bf16_t *a, const pl_linalg_int_t *lda, const pl_linalg_bf16_t *x, const pl_linalg_int_t *incx, const float *beta, float *y, const pl_linalg_int_t *incy, ... );
void sbger_(const pl_linalg_int_t *m, const pl_linalg_int_t *n, const float *alpha, const pl_linalg_bf16_t *x, const pl_linalg_int_t *incx, const pl_linalg_bf16_t *y, const pl_linalg_int_t *incy, float *a, const pl_linalg_int_t *lda);
void sbgerb_(const pl_linalg_int_t *m, const pl_linalg_int_t *n, const float *alpha, const pl_linalg_bf16_t *x, const pl_linalg_int_t *incx, const pl_linalg_bf16_t *y, const pl_linalg_int_t *incy, const float *beta, float *a, const pl_linalg_int_t *lda);
void baxpby_(const pl_linalg_int_t *n, const pl_linalg_bf16_t *alpha, const pl_linalg_bf16_t *x, const pl_linalg_int_t *incx, const pl_linalg_bf16_t *beta, pl_linalg_bf16_t *y, const pl_linalg_int_t *incy);
void baxpy_(const pl_linalg_int_t *n, const pl_linalg_bf16_t *alpha, const pl_linalg_bf16_t *x, const pl_linalg_int_t *incx, pl_linalg_bf16_t *y, const pl_linalg_int_t *incy);
void bcopy_(const pl_linalg_int_t *n, const pl_linalg_bf16_t *x, const pl_linalg_int_t *incx, pl_linalg_bf16_t *y, const pl_linalg_int_t *incy);
#if _PERFLIBS_BF16_INTERFACE == 1
pl_linalg_bf16_t bsbdot_(const pl_linalg_int_t *n, const pl_linalg_bf16_t *b, const pl_linalg_bf16_t *x, const pl_linalg_int_t *incx, const pl_linalg_bf16_t *y, const pl_linalg_int_t *incy);
pl_linalg_bf16_t bdot_(const pl_linalg_int_t *n, const pl_linalg_bf16_t *x, const pl_linalg_int_t *incx, const pl_linalg_bf16_t *y, const pl_linalg_int_t *incy);
#endif
void bgemm_(const char *transa, const char *transb, const pl_linalg_int_t *m, const pl_linalg_int_t *n, const pl_linalg_int_t *k, const pl_linalg_bf16_t *alpha, const pl_linalg_bf16_t *a, const pl_linalg_int_t *lda, const pl_linalg_bf16_t *b, const pl_linalg_int_t *ldb, const pl_linalg_bf16_t *beta, pl_linalg_bf16_t *c, const pl_linalg_int_t *ldc, ... );
void bgemv_(const char *trans, const pl_linalg_int_t *m, const pl_linalg_int_t *n, const pl_linalg_bf16_t *alpha, const pl_linalg_bf16_t *a, const pl_linalg_int_t *lda, const pl_linalg_bf16_t *x, const pl_linalg_int_t *incx, const pl_linalg_bf16_t *beta, pl_linalg_bf16_t *y, const pl_linalg_int_t *incy, ... );
void bger_(const pl_linalg_int_t *m, const pl_linalg_int_t *n, const pl_linalg_bf16_t *alpha, const pl_linalg_bf16_t *x, const pl_linalg_int_t *incx, const pl_linalg_bf16_t *y, const pl_linalg_int_t *incy, pl_linalg_bf16_t *a, const pl_linalg_int_t *lda);
void bgerb_(const pl_linalg_int_t *m, const pl_linalg_int_t *n, const pl_linalg_bf16_t *alpha, const pl_linalg_bf16_t *x, const pl_linalg_int_t *incx, const pl_linalg_bf16_t *y, const pl_linalg_int_t *incy, const pl_linalg_bf16_t *beta, pl_linalg_bf16_t *a, const pl_linalg_int_t *lda);
void bscal_(const pl_linalg_int_t *n, const pl_linalg_bf16_t *alpha, pl_linalg_bf16_t *x, const pl_linalg_int_t *incx);
void hgemm_(const char *transa, const char *transb, const pl_linalg_int_t *m, const pl_linalg_int_t *n, const pl_linalg_int_t *k, const pl_linalg_fp16_t *alpha, const pl_linalg_fp16_t *a, const pl_linalg_int_t *lda, const pl_linalg_fp16_t *b, const pl_linalg_int_t *ldb, const pl_linalg_fp16_t *beta, pl_linalg_fp16_t *c, const pl_linalg_int_t *ldc, ... );
void sgemm_(const char *transa, const char *transb, const pl_linalg_int_t *m, const pl_linalg_int_t *n, const pl_linalg_int_t *k, const float *alpha, const float *a, const pl_linalg_int_t *lda, const float *b, const pl_linalg_int_t *ldb, const float *beta, float *c, const pl_linalg_int_t *ldc, ... );
void sgemm_batch_(const char *transa, const char *transb, const pl_linalg_int_t *m, const pl_linalg_int_t *n, const pl_linalg_int_t *k, const float *alpha, const float *const *a, const pl_linalg_int_t *lda, const float *const *b, const pl_linalg_int_t *ldb, const float *beta, float *const *c, const pl_linalg_int_t *ldc, const pl_linalg_int_t *group_count, const pl_linalg_int_t *group_size, ... );
void sgemmt_(const char *uplo, const char *transa, const char *transb, const pl_linalg_int_t *n, const pl_linalg_int_t *k, const float *alpha, const float *a, const pl_linalg_int_t *lda, const float *b, const pl_linalg_int_t *ldb, const float *beta, float *c, const pl_linalg_int_t *ldc, ... );
void sgemmtr_(const char *uplo, const char *transa, const char *transb, const pl_linalg_int_t *n, const pl_linalg_int_t *k, const float *alpha, const float *a, const pl_linalg_int_t *lda, const float *b, const pl_linalg_int_t *ldb, const float *beta, float *c, const pl_linalg_int_t *ldc, ...);
void sgemv_(const char *trans, const pl_linalg_int_t *m, const pl_linalg_int_t *n, const float *alpha, const float *a, const pl_linalg_int_t *lda, const float *x, const pl_linalg_int_t *incx, const float *beta, float *y, const pl_linalg_int_t *incy, ... );
void sger_(const pl_linalg_int_t *m, const pl_linalg_int_t *n, const float *alpha, const float *x, const pl_linalg_int_t *incx, const float *y, const pl_linalg_int_t *incy, float *a, const pl_linalg_int_t *lda);
void sgerb_(const pl_linalg_int_t *m, const pl_linalg_int_t *n, const float *alpha, const float *x, const pl_linalg_int_t *incx, const float *y, const pl_linalg_int_t *incy, const float *beta, float *a, const pl_linalg_int_t *lda);
float snrm2_(const pl_linalg_int_t *n, const float *x, const pl_linalg_int_t *incx);
void srot_(const pl_linalg_int_t *n, float *x, const pl_linalg_int_t *incx, float *y, const pl_linalg_int_t *incy, const float *c, const float *s);
void srotg_(float *a, float *b, float *c, float *s);
void srotm_(const pl_linalg_int_t *n, float *x, const pl_linalg_int_t *incx, float *y, const pl_linalg_int_t *incy, const float *param);
void srotmg_(float *d1, float *d2, float *b1, const float *b2, float *param);
void ssbmv_(const char *uplo, const pl_linalg_int_t *n, const pl_linalg_int_t *k, const float *alpha, const float *a, const pl_linalg_int_t *lda, const float *x, const pl_linalg_int_t *incx, const float *beta, float *y, const pl_linalg_int_t *incy, ... );
void sscal_(const pl_linalg_int_t *n, const float *alpha, float *x, const pl_linalg_int_t *incx);
void sspmv_(const char *uplo, const pl_linalg_int_t *n, const float *alpha, const float *ap, const float *x, const pl_linalg_int_t *incx, const float *beta, float *y, const pl_linalg_int_t *incy, ... );
void sspr2_(const char *uplo, const pl_linalg_int_t *n, const float *alpha, const float *x, const pl_linalg_int_t *incx, const float *y, const pl_linalg_int_t *incy, float *ap, ... );
void sspr_(const char *uplo, const pl_linalg_int_t *n, const float *alpha, const float *x, const pl_linalg_int_t *incx, float *ap, ... );
void sswap_(const pl_linalg_int_t *n, float *x, const pl_linalg_int_t *incx, float *y, const pl_linalg_int_t *incy);
void ssymm_(const char *side, const char *uplo, const pl_linalg_int_t *m, const pl_linalg_int_t *n, const float *alpha, const float *a, const pl_linalg_int_t *lda, const float *b, const pl_linalg_int_t *ldb, const float *beta, float *c, const pl_linalg_int_t *ldc, ... );
void ssymv_(const char *uplo, const pl_linalg_int_t *n, const float *alpha, const float *a, const pl_linalg_int_t *lda, const float *x, const pl_linalg_int_t *incx, const float *beta, float *y, const pl_linalg_int_t *incy, ... );
void ssyr2_(const char *uplo, const pl_linalg_int_t *n, const float *alpha, const float *x, const pl_linalg_int_t *incx, const float *y, const pl_linalg_int_t *incy, float *a, const pl_linalg_int_t *lda, ... );
void ssyr2k_(const char *uplo, const char *trans, const pl_linalg_int_t *n, const pl_linalg_int_t *k, const float *alpha, const float *a, const pl_linalg_int_t *lda, const float *b, const pl_linalg_int_t *ldb, const float *beta, float *c, const pl_linalg_int_t *ldc, ... );
void ssyr_(const char *uplo, const pl_linalg_int_t *n, const float *alpha, const float *x, const pl_linalg_int_t *incx, float *a, const pl_linalg_int_t *lda, ... );
void ssyrk_(const char *uplo, const char *trans, const pl_linalg_int_t *n, const pl_linalg_int_t *k, const float *alpha, const float *a, const pl_linalg_int_t *lda, const float *beta, float *c, const pl_linalg_int_t *ldc, ... );
void stbmv_(const char *uplo, const char *trans, const char *diag, const pl_linalg_int_t *n, const pl_linalg_int_t *k, const float *a, const pl_linalg_int_t *lda, float *x, const pl_linalg_int_t *incx, ... );
void stbsv_(const char *uplo, const char *trans, const char *diag, const pl_linalg_int_t *n, const pl_linalg_int_t *k, const float *a, const pl_linalg_int_t *lda, float *x, const pl_linalg_int_t *incx, ... );
void stpmv_(const char *uplo, const char *trans, const char *diag, const pl_linalg_int_t *n, const float *ap, float *x, const pl_linalg_int_t *incx, ... );
void stpsv_(const char *uplo, const char *trans, const char *diag, const pl_linalg_int_t *n, const float *ap, float *x, const pl_linalg_int_t *incx, ... );
void strmm_(const char *side, const char *uplo, const char *transa, const char *diag, const pl_linalg_int_t *m, const pl_linalg_int_t *n, const float *alpha, const float *a, const pl_linalg_int_t *lda, float *b, const pl_linalg_int_t *ldb, ... );
void strmv_(const char *uplo, const char *trans, const char *diag, const pl_linalg_int_t *n, const float *a, const pl_linalg_int_t *lda, float *x, const pl_linalg_int_t *incx, ... );
void strsm_(const char *side, const char *uplo, const char *transa, const char *diag, const pl_linalg_int_t *m, const pl_linalg_int_t *n, const float *alpha, const float *a, const pl_linalg_int_t *lda, float *b, const pl_linalg_int_t *ldb, ... );
void strsv_(const char *uplo, const char *trans, const char *diag, const pl_linalg_int_t *n, const float *a, const pl_linalg_int_t *lda, float *x, const pl_linalg_int_t *incx, ... );
void swaxpby_(const pl_linalg_int_t *n, const float *alpha, const float *x, const pl_linalg_int_t *incx, const float *beta, const float *y, const pl_linalg_int_t *incy, float *w, const pl_linalg_int_t *incw);
void xerbla_(const char *srname, const pl_linalg_int_t *info, ... );
void zaxpby_(const pl_linalg_int_t *n, const pl_linalg_doublecomplex_t *alpha, const pl_linalg_doublecomplex_t *x, const pl_linalg_int_t *incx, const pl_linalg_doublecomplex_t *beta, pl_linalg_doublecomplex_t *y, const pl_linalg_int_t *incy);
void zaxpy_(const pl_linalg_int_t *n, const pl_linalg_doublecomplex_t *alpha, const pl_linalg_doublecomplex_t *x, const pl_linalg_int_t *incx, pl_linalg_doublecomplex_t *y, const pl_linalg_int_t *incy);
void zcopy_(const pl_linalg_int_t *n, const pl_linalg_doublecomplex_t *x, const pl_linalg_int_t *incx, pl_linalg_doublecomplex_t *y, const pl_linalg_int_t *incy);
#if !defined(PL_LINALG_AVOID_DOUBLECOMPLEX_RETURN)
pl_linalg_doublecomplex_t zdotc_(const pl_linalg_int_t *n, const pl_linalg_doublecomplex_t *x, const pl_linalg_int_t *incx, const pl_linalg_doublecomplex_t *y, const pl_linalg_int_t *incy);
pl_linalg_doublecomplex_t zdotu_(const pl_linalg_int_t *n, const pl_linalg_doublecomplex_t *x, const pl_linalg_int_t *incx, const pl_linalg_doublecomplex_t *y, const pl_linalg_int_t *incy);
#endif
void zdrot_(const pl_linalg_int_t *n, pl_linalg_doublecomplex_t *x, const pl_linalg_int_t *incx, pl_linalg_doublecomplex_t *y, const pl_linalg_int_t *incy, const double *c, const double *s);
void zdscal_(const pl_linalg_int_t *n, const double *alpha, pl_linalg_doublecomplex_t *x, const pl_linalg_int_t *incx);
void zgbmv_(const char *trans, const pl_linalg_int_t *m, const pl_linalg_int_t *n, const pl_linalg_int_t *kl, const pl_linalg_int_t *ku, const pl_linalg_doublecomplex_t *alpha, const pl_linalg_doublecomplex_t *a, const pl_linalg_int_t *lda, const pl_linalg_doublecomplex_t *x, const pl_linalg_int_t *incx, const pl_linalg_doublecomplex_t *beta, pl_linalg_doublecomplex_t *y, const pl_linalg_int_t *incy, ... );
void zgemm_(const char *transa, const char *transb, const pl_linalg_int_t *m, const pl_linalg_int_t *n, const pl_linalg_int_t *k, const pl_linalg_doublecomplex_t *alpha, const pl_linalg_doublecomplex_t *a, const pl_linalg_int_t *lda, const pl_linalg_doublecomplex_t *b, const pl_linalg_int_t *ldb, const pl_linalg_doublecomplex_t *beta, pl_linalg_doublecomplex_t *c, const pl_linalg_int_t *ldc, ... );
void zgemm3m_(const char *transa, const char *transb, const pl_linalg_int_t *m, const pl_linalg_int_t *n, const pl_linalg_int_t *k, const pl_linalg_doublecomplex_t *alpha, const pl_linalg_doublecomplex_t *a, const pl_linalg_int_t *lda, const pl_linalg_doublecomplex_t *b, const pl_linalg_int_t *ldb, const pl_linalg_doublecomplex_t *beta, pl_linalg_doublecomplex_t *c, const pl_linalg_int_t *ldc, ... );
void zgemm_batch_(const char *transa, const char *transb, const pl_linalg_int_t *m, const pl_linalg_int_t *n, const pl_linalg_int_t *k, const pl_linalg_doublecomplex_t *alpha, const pl_linalg_doublecomplex_t *const *a, const pl_linalg_int_t *lda, const pl_linalg_doublecomplex_t *const *b, const pl_linalg_int_t *ldb, const pl_linalg_doublecomplex_t *beta, pl_linalg_doublecomplex_t *const *c, const pl_linalg_int_t *ldc, const pl_linalg_int_t *group_count, const pl_linalg_int_t *group_size, ... );
void zgemmt_(const char *uplo, const char *transa, const char *transb, const pl_linalg_int_t *n, const pl_linalg_int_t *k, const pl_linalg_doublecomplex_t *alpha, const pl_linalg_doublecomplex_t *a, const pl_linalg_int_t *lda, const pl_linalg_doublecomplex_t *b, const pl_linalg_int_t *ldb, const pl_linalg_doublecomplex_t *beta, pl_linalg_doublecomplex_t *c, const pl_linalg_int_t *ldc, ... );
void zgemmtr_(const char *uplo, const char *transa, const char *transb, const pl_linalg_int_t *n, const pl_linalg_int_t *k, const pl_linalg_doublecomplex_t *alpha, const pl_linalg_doublecomplex_t *a, const pl_linalg_int_t *lda, const pl_linalg_doublecomplex_t *b, const pl_linalg_int_t *ldb, const pl_linalg_doublecomplex_t *beta, pl_linalg_doublecomplex_t *c, const pl_linalg_int_t *ldc, ... );
void zgemv_(const char *trans, const pl_linalg_int_t *m, const pl_linalg_int_t *n, const pl_linalg_doublecomplex_t *alpha, const pl_linalg_doublecomplex_t *a, const pl_linalg_int_t *lda, const pl_linalg_doublecomplex_t *x, const pl_linalg_int_t *incx, const pl_linalg_doublecomplex_t *beta, pl_linalg_doublecomplex_t *y, const pl_linalg_int_t *incy, ... );
void zgerbc_(const pl_linalg_int_t *m, const pl_linalg_int_t *n, const pl_linalg_doublecomplex_t *alpha, const pl_linalg_doublecomplex_t *x, const pl_linalg_int_t *incx, const pl_linalg_doublecomplex_t *y, const pl_linalg_int_t *incy, const pl_linalg_doublecomplex_t *beta, pl_linalg_doublecomplex_t *a, const pl_linalg_int_t *lda);
void zgerbu_(const pl_linalg_int_t *m, const pl_linalg_int_t *n, const pl_linalg_doublecomplex_t *alpha, const pl_linalg_doublecomplex_t *x, const pl_linalg_int_t *incx, const pl_linalg_doublecomplex_t *y, const pl_linalg_int_t *incy, const pl_linalg_doublecomplex_t *beta, pl_linalg_doublecomplex_t *a, const pl_linalg_int_t *lda);
void zgerc_(const pl_linalg_int_t *m, const pl_linalg_int_t *n, const pl_linalg_doublecomplex_t *alpha, const pl_linalg_doublecomplex_t *x, const pl_linalg_int_t *incx, const pl_linalg_doublecomplex_t *y, const pl_linalg_int_t *incy, pl_linalg_doublecomplex_t *a, const pl_linalg_int_t *lda);
void zgeru_(const pl_linalg_int_t *m, const pl_linalg_int_t *n, const pl_linalg_doublecomplex_t *alpha, const pl_linalg_doublecomplex_t *x, const pl_linalg_int_t *incx, const pl_linalg_doublecomplex_t *y, const pl_linalg_int_t *incy, pl_linalg_doublecomplex_t *a, const pl_linalg_int_t *lda);
void zhbmv_(const char *uplo, const pl_linalg_int_t *n, const pl_linalg_int_t *k, const pl_linalg_doublecomplex_t *alpha, const pl_linalg_doublecomplex_t *a, const pl_linalg_int_t *lda, const pl_linalg_doublecomplex_t *x, const pl_linalg_int_t *incx, const pl_linalg_doublecomplex_t *beta, pl_linalg_doublecomplex_t *y, const pl_linalg_int_t *incy, ... );
void zhemm_(const char *side, const char *uplo, const pl_linalg_int_t *m, const pl_linalg_int_t *n, const pl_linalg_doublecomplex_t *alpha, const pl_linalg_doublecomplex_t *a, const pl_linalg_int_t *lda, const pl_linalg_doublecomplex_t *b, const pl_linalg_int_t *ldb, const pl_linalg_doublecomplex_t *beta, pl_linalg_doublecomplex_t *c, const pl_linalg_int_t *ldc, ... );
void zhemv_(const char *uplo, const pl_linalg_int_t *n, const pl_linalg_doublecomplex_t *alpha, const pl_linalg_doublecomplex_t *a, const pl_linalg_int_t *lda, const pl_linalg_doublecomplex_t *x, const pl_linalg_int_t *incx, const pl_linalg_doublecomplex_t *beta, pl_linalg_doublecomplex_t *y, const pl_linalg_int_t *incy, ... );
void zher2_(const char *uplo, const pl_linalg_int_t *n, const pl_linalg_doublecomplex_t *alpha, const pl_linalg_doublecomplex_t *x, const pl_linalg_int_t *incx, const pl_linalg_doublecomplex_t *y, const pl_linalg_int_t *incy, pl_linalg_doublecomplex_t *a, const pl_linalg_int_t *lda, ... );
void zher2k_(const char *uplo, const char *trans, const pl_linalg_int_t *n, const pl_linalg_int_t *k, const pl_linalg_doublecomplex_t *alpha, const pl_linalg_doublecomplex_t *a, const pl_linalg_int_t *lda, const pl_linalg_doublecomplex_t *b, const pl_linalg_int_t *ldb, const double *beta, pl_linalg_doublecomplex_t *c, const pl_linalg_int_t *ldc, ... );
void zher_(const char *uplo, const pl_linalg_int_t *n, const double *alpha, const pl_linalg_doublecomplex_t *x, const pl_linalg_int_t *incx, pl_linalg_doublecomplex_t *a, const pl_linalg_int_t *lda, ... );
void zherk_(const char *uplo, const char *trans, const pl_linalg_int_t *n, const pl_linalg_int_t *k, const double *alpha, const pl_linalg_doublecomplex_t *a, const pl_linalg_int_t *lda, const double *beta, pl_linalg_doublecomplex_t *c, const pl_linalg_int_t *ldc, ... );
void zhpmv_(const char *uplo, const pl_linalg_int_t *n, const pl_linalg_doublecomplex_t *alpha, const pl_linalg_doublecomplex_t *a, const pl_linalg_doublecomplex_t *x, const pl_linalg_int_t *incx, const pl_linalg_doublecomplex_t *beta, pl_linalg_doublecomplex_t *y, const pl_linalg_int_t *incy, ... );
void zhpr2_(const char *uplo, const pl_linalg_int_t *n, const pl_linalg_doublecomplex_t *alpha, const pl_linalg_doublecomplex_t *x, const pl_linalg_int_t *incx, const pl_linalg_doublecomplex_t *y, const pl_linalg_int_t *incy, pl_linalg_doublecomplex_t *a, ... );
void zhpr_(const char *uplo, const pl_linalg_int_t *n, const double *alpha, const pl_linalg_doublecomplex_t *x, const pl_linalg_int_t *incx, pl_linalg_doublecomplex_t *a, ... );
void zrotg_(pl_linalg_doublecomplex_t *ca, const pl_linalg_doublecomplex_t *cb, double *c, pl_linalg_doublecomplex_t *s);
void zsbmv_(const char *uplo, const pl_linalg_int_t *n, const pl_linalg_int_t *k, const pl_linalg_doublecomplex_t *alpha, const pl_linalg_doublecomplex_t *a, const pl_linalg_int_t *lda, const pl_linalg_doublecomplex_t *x, const pl_linalg_int_t *incx, const pl_linalg_doublecomplex_t *beta, pl_linalg_doublecomplex_t *y, const pl_linalg_int_t *incy, ... );
void zscal_(const pl_linalg_int_t *n, const pl_linalg_doublecomplex_t *alpha, pl_linalg_doublecomplex_t *x, const pl_linalg_int_t *incx);
void zswap_(const pl_linalg_int_t *n, pl_linalg_doublecomplex_t *x, const pl_linalg_int_t *incx, pl_linalg_doublecomplex_t *y, const pl_linalg_int_t *incy);
void zsymm_(const char *side, const char *uplo, const pl_linalg_int_t *m, const pl_linalg_int_t *n, const pl_linalg_doublecomplex_t *alpha, const pl_linalg_doublecomplex_t *a, const pl_linalg_int_t *lda, const pl_linalg_doublecomplex_t *b, const pl_linalg_int_t *ldb, const pl_linalg_doublecomplex_t *beta, pl_linalg_doublecomplex_t *c, const pl_linalg_int_t *ldc, ... );
void zsyr2k_(const char *uplo, const char *trans, const pl_linalg_int_t *n, const pl_linalg_int_t *k, const pl_linalg_doublecomplex_t *alpha, const pl_linalg_doublecomplex_t *a, const pl_linalg_int_t *lda, const pl_linalg_doublecomplex_t *b, const pl_linalg_int_t *ldb, const pl_linalg_doublecomplex_t *beta, pl_linalg_doublecomplex_t *c, const pl_linalg_int_t *ldc, ... );
void zsyrk_(const char *uplo, const char *trans, const pl_linalg_int_t *n, const pl_linalg_int_t *k, const pl_linalg_doublecomplex_t *alpha, const pl_linalg_doublecomplex_t *a, const pl_linalg_int_t *lda, const pl_linalg_doublecomplex_t *beta, pl_linalg_doublecomplex_t *c, const pl_linalg_int_t *ldc, ... );
void ztbmv_(const char *uplo, const char *trans, const char *diag, const pl_linalg_int_t *n, const pl_linalg_int_t *k, const pl_linalg_doublecomplex_t *a, const pl_linalg_int_t *lda, pl_linalg_doublecomplex_t *x, const pl_linalg_int_t *incx, ... );
void ztbsv_(const char *uplo, const char *trans, const char *diag, const pl_linalg_int_t *n, const pl_linalg_int_t *k, const pl_linalg_doublecomplex_t *a, const pl_linalg_int_t *lda, pl_linalg_doublecomplex_t *x, const pl_linalg_int_t *incx, ... );
void ztpmv_(const char *uplo, const char *trans, const char *diag, const pl_linalg_int_t *n, const pl_linalg_doublecomplex_t *ap, pl_linalg_doublecomplex_t *x, const pl_linalg_int_t *incx, ... );
void ztpsv_(const char *uplo, const char *trans, const char *diag, const pl_linalg_int_t *n, const pl_linalg_doublecomplex_t *ap, pl_linalg_doublecomplex_t *x, const pl_linalg_int_t *incx, ... );
void ztrmm_(const char *side, const char *uplo, const char *transa, const char *diag, const pl_linalg_int_t *m, const pl_linalg_int_t *n, const pl_linalg_doublecomplex_t *alpha, const pl_linalg_doublecomplex_t *a, const pl_linalg_int_t *lda, pl_linalg_doublecomplex_t *b, const pl_linalg_int_t *ldb, ... );
void ztrmv_(const char *uplo, const char *trans, const char *diag, const pl_linalg_int_t *n, const pl_linalg_doublecomplex_t *a, const pl_linalg_int_t *lda, pl_linalg_doublecomplex_t *x, const pl_linalg_int_t *incx, ... );
void ztrsm_(const char *side, const char *uplo, const char *transa, const char *diag, const pl_linalg_int_t *m, const pl_linalg_int_t *n, const pl_linalg_doublecomplex_t *alpha, const pl_linalg_doublecomplex_t *a, const pl_linalg_int_t *lda, pl_linalg_doublecomplex_t *b, const pl_linalg_int_t *ldb, ... );
void ztrsv_(const char *uplo, const char *trans, const char *diag, const pl_linalg_int_t *n, const pl_linalg_doublecomplex_t *a, const pl_linalg_int_t *lda, pl_linalg_doublecomplex_t *x, const pl_linalg_int_t *incx, ... );
void zwaxpby_(const pl_linalg_int_t *n, const pl_linalg_doublecomplex_t *alpha, const pl_linalg_doublecomplex_t *x, const pl_linalg_int_t *incx, const pl_linalg_doublecomplex_t *beta, const pl_linalg_doublecomplex_t *y, const pl_linalg_int_t *incy, pl_linalg_doublecomplex_t *w, const pl_linalg_int_t *incw);

/* BLAS-like extensions */
void comatadd(char order, char transa, char transb, pl_linalg_int_t m, pl_linalg_int_t n, pl_linalg_singlecomplex_t alpha, const pl_linalg_singlecomplex_t *a, pl_linalg_int_t lda, pl_linalg_singlecomplex_t beta, const pl_linalg_singlecomplex_t *b, pl_linalg_int_t ldb, pl_linalg_singlecomplex_t *c, pl_linalg_int_t ldc);
void comatcopy(char order, char transa, pl_linalg_int_t m, pl_linalg_int_t n, pl_linalg_singlecomplex_t alpha, const pl_linalg_singlecomplex_t *a, pl_linalg_int_t lda, pl_linalg_singlecomplex_t *b, pl_linalg_int_t ldb);
void cimatadd(char order, char transa, char transb, pl_linalg_int_t m, pl_linalg_int_t n, pl_linalg_singlecomplex_t alpha, pl_linalg_singlecomplex_t *a, pl_linalg_int_t lda, pl_linalg_singlecomplex_t beta, const pl_linalg_singlecomplex_t *b, pl_linalg_int_t ldb);
void cimatcopy(char order, char transa, pl_linalg_int_t m, pl_linalg_int_t n, pl_linalg_singlecomplex_t alpha, pl_linalg_singlecomplex_t *a, pl_linalg_int_t lda, pl_linalg_int_t ldb);
void domatadd(char order, char transa, char transb, pl_linalg_int_t m, pl_linalg_int_t n, double alpha, const double *a, pl_linalg_int_t lda, double beta, const double *b, pl_linalg_int_t ldb, double *c, pl_linalg_int_t ldc);
void domatcopy(char order, char transa, pl_linalg_int_t m, pl_linalg_int_t n, double alpha, const double *a, pl_linalg_int_t lda, double *b, pl_linalg_int_t ldb);
void dimatadd(char order, char transa, char transb, pl_linalg_int_t m, pl_linalg_int_t n, double alpha, double *a, pl_linalg_int_t lda, double beta, const double *b, pl_linalg_int_t ldb);
void dimatcopy(char order, char transa, pl_linalg_int_t m, pl_linalg_int_t n, double alpha, double *a, pl_linalg_int_t lda, pl_linalg_int_t ldb);
void somatadd(char order, char transa, char transb, pl_linalg_int_t m, pl_linalg_int_t n, float alpha, const float *a, pl_linalg_int_t lda, float beta, const float *b, pl_linalg_int_t ldb, float *c, pl_linalg_int_t ldc);
void simatadd(char order, char transa, char transb, pl_linalg_int_t m, pl_linalg_int_t n, float alpha, float *a, pl_linalg_int_t lda, float beta, const float *b, pl_linalg_int_t ldb);
void simatcopy(char order, char transa, pl_linalg_int_t m, pl_linalg_int_t n, float alpha, float *a, pl_linalg_int_t lda, pl_linalg_int_t ldb);
void somatcopy(char order, char transa, pl_linalg_int_t m, pl_linalg_int_t n, float alpha, const float *a, pl_linalg_int_t lda, float *b, pl_linalg_int_t ldb);
void zomatadd(char order, char transa, char transb, pl_linalg_int_t m, pl_linalg_int_t n, pl_linalg_doublecomplex_t alpha, const pl_linalg_doublecomplex_t *a, pl_linalg_int_t lda, pl_linalg_doublecomplex_t beta, const pl_linalg_doublecomplex_t *b, pl_linalg_int_t ldb, pl_linalg_doublecomplex_t *c, pl_linalg_int_t ldc);
void zimatadd(char order, char transa, char transb, pl_linalg_int_t m, pl_linalg_int_t n, pl_linalg_doublecomplex_t alpha, pl_linalg_doublecomplex_t *a, pl_linalg_int_t lda, pl_linalg_doublecomplex_t beta, const pl_linalg_doublecomplex_t *b, pl_linalg_int_t ldb);
void zimatcopy(char order, char transa, pl_linalg_int_t m, pl_linalg_int_t n, pl_linalg_doublecomplex_t alpha, pl_linalg_doublecomplex_t *a, pl_linalg_int_t lda, pl_linalg_int_t ldb);
void zomatcopy(char order, char transa, pl_linalg_int_t m, pl_linalg_int_t n, pl_linalg_doublecomplex_t alpha, const pl_linalg_doublecomplex_t *a, pl_linalg_int_t lda, pl_linalg_doublecomplex_t *b, pl_linalg_int_t ldb);

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif  /* !defined(_PERFLIBS_BLAS_H) */
